<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC6-DX-6GN5NK2" ignored="0" name="Test" tests="2" failures="1" timestamp="28 May 2019 07:27:14 GMT" time="7.171" errors="0">
  <testcase name="met1" time="0.016" classname="TestNGdemo.Softasert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Hell] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hell] but found [Hello]
at TestNGdemo.Softasert.met1(Softasert.java:16)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- met1 -->
  <testcase name="homepage" time="6.689" classname="TestNGdemo.selncode1"/>
</testsuite> <!-- Test -->
